import {
  BookmarkSimple,
  Briefcase,
  Baby,
  Gift,
  TShirt,
  FilmSlate,
  Pizza,
  Drop,
  Lightning,
  DeviceMobile,
  WifiHigh,
  Dog,
  Cat,
  Bicycle,
  Train,
  Flower,
  BookOpen,
  MusicNotes,
  Barbell,
  Bed,
  PaintBrush,
  Camera,
  Suitcase,
  Wine,
  Coins,
  Wrench,
  Scissors,
  Desktop,
  Storefront,
} from "@phosphor-icons/react";
import {
  House,
  ArrowsDownUp,
  ChartDonut,
  Wallet,
  Crown,
  GearSix,
  Plus,
  ArrowUpRight,
  ArrowDownLeft,
  CaretLeft,
  CaretRight,
  CaretDown,
  X,
  Check,
  DownloadSimple,
  UploadSimple,
  MagnifyingGlass,
  Bell,
  SignOut,
  Trash,
  PencilSimple,
  ForkKnife,
  ShoppingBag,
  Car,
  GameController,
  Heart,
  Basket,
  Sparkle,
  Coffee,
  Airplane,
  GraduationCap,
  PawPrint,
  LockSimple,
  ArrowRight,
  CalendarBlank,
  DotsThree,
  EnvelopeSimple,
  Calculator,
  CheckCircle,
  WarningCircle,
  ShieldCheck,
  CloudCheck,
  CloudSlash,
  ArrowClockwise,
  CreditCard,
  GoogleLogo,
  Leaf,
  Info,
  SlidersHorizontal,
  FileText,
  GlobeHemisphereWest,
  Sun,
  UserCircle,
} from "@phosphor-icons/react";
const icons = {
  bookmark: BookmarkSimple,
  briefcase: Briefcase,
  baby: Baby,
  gift: Gift,
  tshirt: TShirt,
  film: FilmSlate,
  pizza: Pizza,
  drop: Drop,
  electricity: Lightning,
  phone: DeviceMobile,
  wifi: WifiHigh,
  dog: Dog,
  cat: Cat,
  bicycle: Bicycle,
  train: Train,
  flower: Flower,
  book: BookOpen,
  music: MusicNotes,
  gym: Barbell,
  bed: Bed,
  art: PaintBrush,
  camera: Camera,
  suitcase: Suitcase,
  wine: Wine,
  coins: Coins,
  repair: Wrench,
  haircut: Scissors,
  desktop: Desktop,
  store: Storefront,
  house: House,
  transactions: ArrowsDownUp,
  report: ChartDonut,
  wallet: Wallet,
  crown: Crown,
  settings: GearSix,
  plus: Plus,
  up: ArrowUpRight,
  down: ArrowDownLeft,
  left: CaretLeft,
  right: CaretRight,
  chevron: CaretDown,
  close: X,
  check: Check,
  download: DownloadSimple,
  upload: UploadSimple,
  search: MagnifyingGlass,
  bell: Bell,
  logout: SignOut,
  trash: Trash,
  edit: PencilSimple,
  fork: ForkKnife,
  bag: ShoppingBag,
  car: Car,
  game: GameController,
  heart: Heart,
  basket: Basket,
  sparkle: Sparkle,
  coffee: Coffee,
  plane: Airplane,
  study: GraduationCap,
  pet: PawPrint,
  lock: LockSimple,
  arrow: ArrowRight,
  calendar: CalendarBlank,
  dots: DotsThree,
  email: EnvelopeSimple,
  calculator: Calculator,
  success: CheckCircle,
  warning: WarningCircle,
  shield: ShieldCheck,
  cloud: CloudCheck,
  offline: CloudSlash,
  reset: ArrowClockwise,
  card: CreditCard,
  google: GoogleLogo,
  leaf: Leaf,
  info: Info,
  sliders: SlidersHorizontal,
  file: FileText,
  globe: GlobeHemisphereWest,
  sun: Sun,
  user: UserCircle,
};
export type IconName = keyof typeof icons;
export default function Icon({
  name,
  size = 22,
  filled = false,
  className = "",
}: {
  name: string;
  size?: number;
  filled?: boolean;
  className?: string;
}) {
  const Component = icons[name as IconName] ?? Sparkle;
  return (
    <Component
      size={size}
      weight={filled ? "fill" : "regular"}
      className={className}
      aria-hidden="true"
    />
  );
}
